### ISSUE TITLE
alarm-notifier pluginCustomization file

### ISSUE THREAD

**Issue by lotrus** [ControlSystemStudio/org.csstudio.sns#3]
I'm launching alarm-notifier (nightly build) with the following command:
```./alarm-notifier -root Annunciator -pluginCustomization ../alarmPreferences.ini```

and I have the following error message:
```Alarm Notification 4.0.3.201611090159
Configuration Root: Annunciator
JMS Server Topic:   Annunciator_SERVER
JMS Client Topic:   Annunciator_CLIENT
JMS Global Topic:   GLOBAL_SERVER
Notifier timer threshold: 100
Notifie only escalating alarms: false
2017-06-30 09:21:38.033 INFO [Thread 1] org.csstudio.alarm.beast.notifier.AlarmNotifier (start) - Alarm Notifier started
2017-06-30 09:21:38.227 SEVERE [Thread 19] org.csstudio.alarm.beast.ui.clientmodel.AlarmClientModel (readConfiguration) - Cannot connect to RDB
java.lang.Exception: Cannot connect to database, Access denied for user 'alarm'@'localhost' (using password: YES)
	at org.csstudio.alarm.beast.client.AlarmConfiguration.<init>(AlarmConfiguration.java:98)
	at org.csstudio.alarm.beast.client.AlarmConfiguration.<init>(AlarmConfiguration.java:125)
	at org.csstudio.alarm.beast.ui.clientmodel.AlarmClientModel$1.<init>(AlarmClientModel.java:398)
	at org.csstudio.alarm.beast.ui.clientmodel.AlarmClientModel.readConfiguration(AlarmClientModel.java:398)
	at org.csstudio.alarm.beast.ui.clientmodel.ReadConfigJob.run(ReadConfigJob.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Access denied for user 'alarm'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1665)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1207)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2249)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2280)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2079)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.csstudio.platform.utility.rdb.internal.MySQL_RDB.connect(MySQL_RDB.java:56)
	at org.csstudio.platform.utility.rdb.RDBUtil.<init>(RDBUtil.java:179)
	at org.csstudio.platform.utility.rdb.RDBUtil.connect(RDBUtil.java:143)
	at org.csstudio.alarm.beast.client.AlarmConfiguration.<init>(AlarmConfiguration.java:94)
	... 5 more

2017-06-30 09:21:38.228 CONFIG [Thread 19] org.csstudio.alarm.beast.notifier.AlarmNotifier (handleNewAlarmConfiguration) - New alarm configuration loaded, pending actions interrupted
```

I can see that alarm-notifier is not taking account the user specified in alarmPreferences.ini who is not 'alarm'.
The same command is working with an older alarm-notifier.

**Comment by kasemir** [comment]
>I can see that alarm-notifier is not taking account the user specified in alarmPreferences.ini

There is unfortunately no error message if the file is not found, if "alarmPreferences.ini" is mistyped etc. The current working directory of the JVM may also not be what you think it is when  you start the program, so try the absolute path name:
` ./alarm-notifier -root Annunciator -pluginCustomization /full/path/to/your/alarmPreferences.ini`

**Comment by lotrus** [comment]
It's working with the full path, thanks for you're help.
